sudo: required

services:
  - docker

language: node_js

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '10'

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm i -g @settlemint/mint-cli ganache-cli
  - ganache-cli -l 0xfffffffffff -i 1337 -m "robot robot robot robot robot robot robot robot robot robot robot robot" > /dev/null &

deploy:
  provider: script
  skip_cleanup: true
  script:
    - bash ./scripts/deploy.sh
  on:
    all_branches: true
    repo: settlemint/databrokerdao-dapi
