sudo: required

services:
  - docker


language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '8'

before_install:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm i -g @settlemint/mint-cli truffle

before_script:
  - mint start
  - sleep 30
  # - mongo 127.0.0.1/mint --eval "var document={address:\"0xa68ed9eaf23dbda03ec192f41598ce2e182cfca5\"};db.authorisedaddresses.insert(document);"

after_success:
  - npm run semantic-release
  - if ([ $TRAVIS_PULL_REQUEST == "false" ]); then
    docker build --build-arg NPM_TOKEN=${NPM_TOKEN} -t settlemint/${PROJECT_NAME}:${TRAVIS_BRANCH} -t settlemint/${PROJECT_NAME}:${TRAVIS_BRANCH}-`date +%s` .;
    docker push settlemint/${PROJECT_NAME};
    fi

after_failure:
  - mint logs mint
