sudo: required

services:
  - docker

language: node_js

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - '9'


before_install:
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}";
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
  - npm i -g @settlemint/mint-cli ganache-cli
  - ganache-cli -l 0xfffffffffff -i 1337 -m "robot robot robot robot robot robot robot robot robot robot robot robot" > /dev/null &

script: echo "npm test temporarily disabled"

after_success:
  - npm run semantic-release
  - if ([ $TRAVIS_PULL_REQUEST == "false" ]); then
    docker build --build-arg NPM_TOKEN=${NPM_TOKEN} -t settlemint/${PROJECT_NAME}:${TRAVIS_BRANCH} -t settlemint/${PROJECT_NAME}:${TRAVIS_BRANCH}-`date +%s` .;
    docker push settlemint/${PROJECT_NAME};
    fi
