version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    links:
      - mongo

  rabbit:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.9
    ports:
      - "15672:15672"
      - "5672:5672"

  ethereum:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: ["node", "./build/cli.node.js", "--secure", "-u" ,"0","--gasPrice", "0", "-l", "0xfffffffffff", "-i", "1337", "-m", 'robot robot robot robot robot robot robot robot robot robot robot robot']

  mint:
    image: settlemint/mint:master
    ports:
      - "3333:3333"
    volumes:
     - .:/srv/project
    environment:
      ETHEREUM_NODE_URL: http://ethereum:8545
    depends_on:
      - mongo
      - ethereum
      - rabbit
    links:
      - mongo
      - ethereum
      - rabbit
